title: "CyberLabs"
email: cyb3rlabs@outlook.com
timezone: UTC
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Cyb3rLabs
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  sal:
    name: cyb3rlabs
    display_name: CyberLabs
    avatar: 'assets/images/sal.png'
    email: cyb3rlabs@outlook.com
    web: https://www.cyb3rlabs.com
    twitter: https://twitter.com/cyb3rlabs
    description: "Main Editor"
  

# Social
social:
  instagram: https://www.instagram.com/cyb3rlabs/
  facebook: https://www.facebook.com/cyb3rlabs
  twitter: https://twitter.com/cyb3rlabs

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives